stages:
  - build
  - publish

docker-build-push:
  stage: build
  only:
    - tags
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add make python3 py-pip
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - make build
    - make build TAG=latest
    - make push
    - make push TAG=latest

pypi-publish:
  stage: publish
  only:
    - tags
  image: python:3.10
  script:
    - python -m pip install twine
    - python python/setup.py sdist bdist_wheel
    - python -u __token__ -p $PYPI_TOKEN -m twine upload --verbose dist/*