image: registry.gitlab.com/mikedoesdatascience/sportsml:0.0.1

stages:
  - upload

nba-upload:
  stage: upload
  script:
    - nba_mongo_upload

nfl-upload:
  stage: upload
  script:
    - nfl_mongo_upload