stages:
  - publish
  - build

pypi-publish:
  stage: publish
  image: python:3.10
  only:
    - tags
  needs: []
  script:
    - python -m pip install twine
    - cd python
    - python setup.py sdist bdist_wheel
    - python -m twine upload -u __token__ -p $PYPI_TOKEN --verbose dist/*

docker-build-push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - tags
  needs: ["pypi-publish"]
  before_script:
    - apk add make python3 py-pip
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - make build-prod
    - make build-prod VERSION=latest
    - make push
    - make push VERSION=latest