image: gitpod/workspace-python-3.11

tasks:
  - name: Setup dev environment
    before: |
      alias ltr='ls -lhtr'
      echo "alias ltr='ls -lhtr'" >> ~/.bashrc
      python -m pip install -U uv
      python -m uv pip install --system --extra-index-url https://download.pytorch.org/whl/cpu -r ./requirements.cpu.lock
      python -m uv pip install --system hatch ruff
      python -m uv pip install --system --no-deps -e .