FROM python:3.11-slim

RUN python -m pip install -U pip

COPY python/requirements.txt /tmp/requirements.txt

RUN python -m pip install -U --no-cache-dir \
        --extra-index-url https://download.pytorch.org/whl/cpu \
        -f https://data.dgl.ai/wheels/repo.html \
        -r /tmp/requirements.txt

CMD ["python", "-m", "pip", "freeze"]