FROM python:3.11-slim

ARG PLATFORM cpu

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=python/requirements.txt,target=requirements.txt \
    python -m pip install -U uv && \
    python -m uv pip install -U --system \
        --extra-index-url https://download.pytorch.org/whl/${PLATFORM} \
        -r requirements.txt

CMD ["python", "-m", "uv", "pip", "freeze", "--color=never", "--system"]