_target_: pytorch_lightning.Trainer
default_root_dir: ${hydra:run.dir}
max_epochs: 20
logger:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${hydra:run.dir}
  name: model
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint